### ISSUE TITLE
override default settings xml

### ISSUE THREAD

**Issue by jbuettnerbild** [s4u/maven-settings-action#2]
if i don't remove the default settings.xml in .m2 i got always the warning "##[warning]maven settings.xml already exists - skip". i must manualy delete the default settings xml before i can generade my custom settings.xml with this action. 

My understanding from a action that generade a settings.xml is that i must not delete some default files before using the action. by the way: it were be nice if somewhere a hint for this litte issue.

**Comment by slawekjaranowski** [comment]
can you give links to project where default settings.xml exist?
or show github action config

**Comment by jbuettnerbild** [comment]
my project is private but here is a part of the yaml and from the github log. the step "maven test and sonar" breaks because the settings.xml not contains my custom server an property values.

**default settings.xml:**
` Run a one-line script0s
  
Run cat /home/runner/.m2/settings.xml

  <settings>
      <servers>
        <server>
          <id>github</id>
          <username>${env.GITHUB_ACTOR}</username>
          <password>${env.GITHUB_TOKEN}</password>
        </server>
      </servers>
  </settings>`

**warning**
` set maven settings xml0s
##[warning]maven settings.xml already exists - skip
Run s4u/maven-settings-action@v1
Prepare maven setings: /home/runner/.m2/settings.xml
##[warning]maven settings.xml already exists - skip`

**part of the job yaml**
`name: CI

on: [push]

jobs:
  test_and_build:    
    name: maven test and docker build
    runs-on: ubuntu-latest

    steps:
      - name: init maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven

      - name: setup jvm
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: rm default settings xml
        run: rm /home/runner/.m2/settings.xml

      - name: set custom settings xml
        uses: s4u/maven-settings-action@v1
        with:
          servers: '[{"id": "*****", "username": "*****", "password": "${{ secrets.***** }}" }]'
          properties: '[{"sonar.projectKey": "*****"}, {"sonar.organization": "*****"}, {"sonar.host.url": "*****"}, {"sonar.login": "${{ secrets.***** }}"}]'

      - name: checkout repository
        uses: actions/checkout@v1

      - name: maven test and sonar
        run: mvn -B -U dependency:resolve clean verify sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
`

**Comment by slawekjaranowski** [comment]
You are right, when you use cache generated settings.xml is added to cache and next time is restored from cache.

We should do two fix:
 - add override options to override existing settings.xml
 - add post task to clean generated file after job - settings can contains sensitive data and shouldn't be cacheable and shouldn't be exist after build

**Comment by jbuettnerbild** [comment]
sounds good. maybe a hint in the readme will be helpful too.

**Comment by slawekjaranowski** [comment]
fix in version **v1.1**
