### ISSUE TITLE
How can I create a server element without username or configuration?

### ISSUE THREAD

**Issue by zhanhb** [s4u/maven-settings-action#269]
The server with id `gpg.passphrase` has only passphrase show as following. But when I try to do so, I got an error of `servers must contain id, and username or configuration`.

```xml
<server>
	<id>gpg.passphrase</id>
	<passphrase>${env.GPG_PASSPHRASE}</passphrase>
</server>
```

**Comment by slawekjaranowski** [comment]
So look like we should required id only.

**Comment by slawekjaranowski** [comment]
It looks like duplicate of #223
