### ISSUE TITLE
Proxy support lacks authentication settings

### ISSUE THREAD

**Issue by nox-4O4** [s4u/maven-settings-action#279]
Some proxies require authentication. There are Maven settings to configure proxy credentials:
https://maven.apache.org/settings.html#proxies
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
  ...
  <proxies>
    <proxy>
      <id>myproxy</id>
      <active>true</active>
      <protocol>http</protocol>
      <host>proxy.somewhere.com</host>
      <port>8080</port>
      <username>proxyuser</username>
      <password>somepassword</password>
      <nonProxyHosts>*.google.com|ibiblio.org</nonProxyHosts>
    </proxy>
  </proxies>
  ...
</settings>
```
(`username` and `password`).

Currently, it is not possible to specify proxy authentification using `proxies` option.

**Comment by slawekjaranowski** [comment]
PR are welcome

**Comment by Gozke** [comment]
Hi There,
I wanted to experiment a little with github actions and take a look into an existing one.. so I took the liberty of fixing this issue. See my PR here: https://github.com/s4u/maven-settings-action/pull/338.

This action's a greate initive. ;) Thanks for your work so far!
