### ISSUE TITLE
Allow adding a custom repository to the settings.xml

### ISSUE THREAD

**Issue by wimdeblauwe** [s4u/maven-settings-action#283]
**Is your feature request related to a problem? Please describe.**
Unless I have misunderstood things, I think that this action assumes you add your repository to your `pom.xml` and just define the authentication part in the `settings.xml`. However, it is not such a good idea to add custom repository URLs in your Maven build file (See https://blog.sonatype.com/2009/02/why-putting-repositories-in-your-poms-is-a-bad-idea/).

**Describe the solution you'd like**
I would like a way to have the action generate a `settings.xml` that has repository entries. Ideally, it would generate something like this:

```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      http://maven.apache.org/xsd/settings-1.0.0.xsd">

  <activeProfiles>
    <activeProfile>github</activeProfile>
  </activeProfiles>

  <profiles>
    <profile>
      <id>github</id>
      <repositories>
        <repository>
          <id>central</id>
          <url>https://repo1.maven.org/maven2</url>
        </repository>
        <repository>
          <id>github</id>
          <url>https://maven.pkg.github.com/MyOrganisation/MyProject</url>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
        </repository>
      </repositories>
    </profile>
  </profiles>

  <servers>
    <server>
      <id>github</id>
      <username>GITHUB_ACTOR</username>
      <password>GITHUB_TOKEN</password>
    </server>
  </servers>
</settings>
```

**Comment by flo-02-mu** [comment]
I made an attempt in https://github.com/s4u/maven-settings-action/pull/319
