### ISSUE TITLE
repositories section missing?

### ISSUE THREAD

**Issue by fclante** [s4u/maven-settings-action#291]
**Is your feature request related to a problem? Please describe.**
I know that the repositories section can be expressed through the pom.xml file, but still I would expect all supported features of the settings.xml file available in an action to replace the manual inclusion of a settings.xml. 

I see that the 'settings-mirrors' property exists, but I don't see any reason to limit the options.

Also from https://maven.apache.org/guides/mini/guide-mirror-settings.html 
- "_The size of the central repository is [increasing steadily](https://search.maven.org/stats) To save us bandwidth and you time, **mirroring the entire central repository is not allowed**. (Doing so will get you automatically banned_."
-  Therefore it would be nice to have the 'settings-repositories' property available

**Describe the solution you'd like**
add a 'settings-repositories' property to the action

**Describe alternatives you've considered**
none.

**Comment by mkoohafkan** [comment]
+1 I'd like to see this too. I think this is the same as #283.
