### ISSUE TITLE
Oracle Maven repository

### ISSUE THREAD

**Issue by geel97** [s4u/maven-settings-action#62]
**Is your feature request related to a problem? Please describe.**
Is not possible to access to Oracle Maven repository.

**Describe the solution you'd like**
This is the configuration needed for Oracle repository.
```xml
 <server>
    <id>maven.oracle.com</id>
    <username>username</username>
    <password>password</password>
    <configuration>
      <basicAuthScope>
        <host>ANY</host>
        <port>ANY</port>
        <realm>OAM 11g</realm>
      </basicAuthScope>
      <httpConfiguration>
        <all>
          <params>
            <property>
              <name>http.protocol.allow-circular-redirects</name>
              <value>%b,true</value>
            </property>
          </params>
        </all>
      </httpConfiguration>
    </configuration>
  </server>
```
It would be nice to have a configuration with this settings.
**Describe alternatives you've considered**
There aren't any other alternative to access that repo.

**Additional context**
https://docs.oracle.com/middleware/1213/core/MAVEN/config_maven_repo.htm#MAVEN9016

**Comment by slawekjaranowski** [comment]
I propose to consider add repository definition to `settings.xml`, point 6.6 from oracle manual.

**Comment by geel97** [comment]
> I propose to consider add repository definition to `settings.xml`, point 6.6 from oracle manual.

I don't understand what you mean. Point [6.6](https://docs.oracle.com/middleware/1213/core/MAVEN/config_maven_repo.htm#MAVEN9017) is describing how to add the Oracle repository directly in `settings.xml`, but I don't need that and it doesn't resolve the issue, since the authentication described in [6.5](https://docs.oracle.com/middleware/1213/core/MAVEN/config_maven_repo.htm#MAVEN9016) is still required.

**Comment by slawekjaranowski** [comment]
Ok, I think about both 

 - [6.5](https://docs.oracle.com/middleware/1213/core/MAVEN/config_maven_repo.htm#MAVEN9016) authentication
 - [6.6](https://docs.oracle.com/middleware/1213/core/MAVEN/config_maven_repo.htm#MAVEN9017) repository definition in settings.xml

Question is: do both feature should be enabled by one option or should be separated feature?

**Comment by geel97** [comment]
Ok. Now I understand what are you thinking.
I think they could be enabled by separate option. I usually prefer to add repositories directly in POM, because sometimes I also need to add Oracle plugin repo beside standard Oracle repo. In fact I use this action only to set servers credentials.
```yml
steps:
- uses: s4u/maven-settings-action@v2.1.2
  with:
    oracleServer: '[{"id": "maven.oracle.com", "username": "username", "password": "password"}]' #with auth configuration
    oracleRepo: false #to add oracle repository (if needed). Maybe also pluginRepository?
```

**Comment by geel97** [comment]
Thanks so much for your work. I have tested it and now it works perfectly!

**Comment by slawekjaranowski** [comment]
Your welcome.
In my work is valuable for you, you can consider a some sponsoring for me.
