### ISSUE TITLE
Cannot authenticate with Github Package

### ISSUE THREAD

**Issue by jimmyd-be** [s4u/maven-settings-action#81]
**Describe the bug**
Cannot download artifacts from Github package from another repo in same account

**To Reproduce**
Try to download artifact from Github Maven package

**Expected behavior**
Authenticate to the Github Maven repo and download the artifact

**Additional context**
https://stackoverflow.com/questions/65267872/github-action-cannot-download-artifact-from-github-package-repository

**Comment by jimmyd-be** [comment]
This is not an isuse of the plugin but it was an misconfigure of my flow. The maven-settings-action need to be placed after the actions/cache action.

**Comment by slawekjaranowski** [comment]
Thanks for reporting.
I think we can add such information to action readme.

If you wish PR will be welcomed.
