### ISSUE TITLE
Allow defining custom configuration for server

### ISSUE THREAD

**Issue by marcindabrowski** [s4u/maven-settings-action#84]
I'm using Azure Maven Plugins to deploy an application to the Azure Web App.
I'm using [Service Principles in settings.xml](https://github.com/microsoft/azure-maven-plugins/wiki/Authentication#service-principles-in-settingsxml).
This setup requires to add to the settings.xml server without username and password, but with custom configuration.

Currently, action requires a username and a password and does not give the ability to define the configuration section.

It will be great that you remove the requirement constraint from username and password and allow define configuration as key-value pairs.

**Comment by slawekjaranowski** [comment]
I hope that, new release will meet your request. 
I'm waiting for feedback.
